// This file was generated by counterfeiter
package volmanfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/volman/voldriver"
	"github.com/cloudfoundry-incubator/volman/voldriver/driverhttp"
)

type FakeRemoteClientFactory struct {
	NewRemoteClientStub        func(url string, tls *voldriver.TLSConfig) (voldriver.Driver, error)
	newRemoteClientMutex       sync.RWMutex
	newRemoteClientArgsForCall []struct {
		url string
		tls *voldriver.TLSConfig
	}
	newRemoteClientReturns struct {
		result1 voldriver.Driver
		result2 error
	}
}

func (fake *FakeRemoteClientFactory) NewRemoteClient(url string, tls *voldriver.TLSConfig) (voldriver.Driver, error) {
	fake.newRemoteClientMutex.Lock()
	fake.newRemoteClientArgsForCall = append(fake.newRemoteClientArgsForCall, struct {
		url string
		tls *voldriver.TLSConfig
	}{url, tls})
	fake.newRemoteClientMutex.Unlock()
	if fake.NewRemoteClientStub != nil {
		return fake.NewRemoteClientStub(url, tls)
	} else {
		return fake.newRemoteClientReturns.result1, fake.newRemoteClientReturns.result2
	}
}

func (fake *FakeRemoteClientFactory) NewRemoteClientCallCount() int {
	fake.newRemoteClientMutex.RLock()
	defer fake.newRemoteClientMutex.RUnlock()
	return len(fake.newRemoteClientArgsForCall)
}

func (fake *FakeRemoteClientFactory) NewRemoteClientArgsForCall(i int) (string, *voldriver.TLSConfig) {
	fake.newRemoteClientMutex.RLock()
	defer fake.newRemoteClientMutex.RUnlock()
	return fake.newRemoteClientArgsForCall[i].url, fake.newRemoteClientArgsForCall[i].tls
}

func (fake *FakeRemoteClientFactory) NewRemoteClientReturns(result1 voldriver.Driver, result2 error) {
	fake.NewRemoteClientStub = nil
	fake.newRemoteClientReturns = struct {
		result1 voldriver.Driver
		result2 error
	}{result1, result2}
}

var _ driverhttp.RemoteClientFactory = new(FakeRemoteClientFactory)
