// Code generated by counterfeiter. DO NOT EDIT.
package volmanfakes

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"code.cloudfoundry.org/volman"
)

type FakePlugin struct {
	GetImplementationStub        func() interface{}
	getImplementationMutex       sync.RWMutex
	getImplementationArgsForCall []struct{}
	getImplementationReturns     struct {
		result1 interface{}
	}
	getImplementationReturnsOnCall map[int]struct {
		result1 interface{}
	}
	MatchesStub        func(lager.Logger, volman.PluginSpec) bool
	matchesMutex       sync.RWMutex
	matchesArgsForCall []struct {
		arg1 lager.Logger
		arg2 volman.PluginSpec
	}
	matchesReturns struct {
		result1 bool
	}
	matchesReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePlugin) GetImplementation() interface{} {
	fake.getImplementationMutex.Lock()
	ret, specificReturn := fake.getImplementationReturnsOnCall[len(fake.getImplementationArgsForCall)]
	fake.getImplementationArgsForCall = append(fake.getImplementationArgsForCall, struct{}{})
	fake.recordInvocation("GetImplementation", []interface{}{})
	fake.getImplementationMutex.Unlock()
	if fake.GetImplementationStub != nil {
		return fake.GetImplementationStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getImplementationReturns.result1
}

func (fake *FakePlugin) GetImplementationCallCount() int {
	fake.getImplementationMutex.RLock()
	defer fake.getImplementationMutex.RUnlock()
	return len(fake.getImplementationArgsForCall)
}

func (fake *FakePlugin) GetImplementationReturns(result1 interface{}) {
	fake.GetImplementationStub = nil
	fake.getImplementationReturns = struct {
		result1 interface{}
	}{result1}
}

func (fake *FakePlugin) GetImplementationReturnsOnCall(i int, result1 interface{}) {
	fake.GetImplementationStub = nil
	if fake.getImplementationReturnsOnCall == nil {
		fake.getImplementationReturnsOnCall = make(map[int]struct {
			result1 interface{}
		})
	}
	fake.getImplementationReturnsOnCall[i] = struct {
		result1 interface{}
	}{result1}
}

func (fake *FakePlugin) Matches(arg1 lager.Logger, arg2 volman.PluginSpec) bool {
	fake.matchesMutex.Lock()
	ret, specificReturn := fake.matchesReturnsOnCall[len(fake.matchesArgsForCall)]
	fake.matchesArgsForCall = append(fake.matchesArgsForCall, struct {
		arg1 lager.Logger
		arg2 volman.PluginSpec
	}{arg1, arg2})
	fake.recordInvocation("Matches", []interface{}{arg1, arg2})
	fake.matchesMutex.Unlock()
	if fake.MatchesStub != nil {
		return fake.MatchesStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.matchesReturns.result1
}

func (fake *FakePlugin) MatchesCallCount() int {
	fake.matchesMutex.RLock()
	defer fake.matchesMutex.RUnlock()
	return len(fake.matchesArgsForCall)
}

func (fake *FakePlugin) MatchesArgsForCall(i int) (lager.Logger, volman.PluginSpec) {
	fake.matchesMutex.RLock()
	defer fake.matchesMutex.RUnlock()
	return fake.matchesArgsForCall[i].arg1, fake.matchesArgsForCall[i].arg2
}

func (fake *FakePlugin) MatchesReturns(result1 bool) {
	fake.MatchesStub = nil
	fake.matchesReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakePlugin) MatchesReturnsOnCall(i int, result1 bool) {
	fake.MatchesStub = nil
	if fake.matchesReturnsOnCall == nil {
		fake.matchesReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.matchesReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakePlugin) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getImplementationMutex.RLock()
	defer fake.getImplementationMutex.RUnlock()
	fake.matchesMutex.RLock()
	defer fake.matchesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePlugin) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ volman.Plugin = new(FakePlugin)
