// This file was generated by counterfeiter
package volmanfakes

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"github.com/cloudfoundry-incubator/voldriver"
	"github.com/cloudfoundry-incubator/volman/vollocal"
)

type FakeDriverFactory struct {
	DiscoverStub        func(logger lager.Logger) (map[string]voldriver.Driver, error)
	discoverMutex       sync.RWMutex
	discoverArgsForCall []struct {
		logger lager.Logger
	}
	discoverReturns struct {
		result1 map[string]voldriver.Driver
		result2 error
	}
	DriverStub        func(logger lager.Logger, driverId string, driverPath, driverFileName string) (voldriver.Driver, error)
	driverMutex       sync.RWMutex
	driverArgsForCall []struct {
		logger         lager.Logger
		driverId       string
		driverPath     string
		driverFileName string
	}
	driverReturns struct {
		result1 voldriver.Driver
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDriverFactory) Discover(logger lager.Logger) (map[string]voldriver.Driver, error) {
	fake.discoverMutex.Lock()
	fake.discoverArgsForCall = append(fake.discoverArgsForCall, struct {
		logger lager.Logger
	}{logger})
	fake.recordInvocation("Discover", []interface{}{logger})
	fake.discoverMutex.Unlock()
	if fake.DiscoverStub != nil {
		return fake.DiscoverStub(logger)
	} else {
		return fake.discoverReturns.result1, fake.discoverReturns.result2
	}
}

func (fake *FakeDriverFactory) DiscoverCallCount() int {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	return len(fake.discoverArgsForCall)
}

func (fake *FakeDriverFactory) DiscoverArgsForCall(i int) lager.Logger {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	return fake.discoverArgsForCall[i].logger
}

func (fake *FakeDriverFactory) DiscoverReturns(result1 map[string]voldriver.Driver, result2 error) {
	fake.DiscoverStub = nil
	fake.discoverReturns = struct {
		result1 map[string]voldriver.Driver
		result2 error
	}{result1, result2}
}

func (fake *FakeDriverFactory) Driver(logger lager.Logger, driverId string, driverPath string, driverFileName string) (voldriver.Driver, error) {
	fake.driverMutex.Lock()
	fake.driverArgsForCall = append(fake.driverArgsForCall, struct {
		logger         lager.Logger
		driverId       string
		driverPath     string
		driverFileName string
	}{logger, driverId, driverPath, driverFileName})
	fake.recordInvocation("Driver", []interface{}{logger, driverId, driverPath, driverFileName})
	fake.driverMutex.Unlock()
	if fake.DriverStub != nil {
		return fake.DriverStub(logger, driverId, driverPath, driverFileName)
	} else {
		return fake.driverReturns.result1, fake.driverReturns.result2
	}
}

func (fake *FakeDriverFactory) DriverCallCount() int {
	fake.driverMutex.RLock()
	defer fake.driverMutex.RUnlock()
	return len(fake.driverArgsForCall)
}

func (fake *FakeDriverFactory) DriverArgsForCall(i int) (lager.Logger, string, string, string) {
	fake.driverMutex.RLock()
	defer fake.driverMutex.RUnlock()
	return fake.driverArgsForCall[i].logger, fake.driverArgsForCall[i].driverId, fake.driverArgsForCall[i].driverPath, fake.driverArgsForCall[i].driverFileName
}

func (fake *FakeDriverFactory) DriverReturns(result1 voldriver.Driver, result2 error) {
	fake.DriverStub = nil
	fake.driverReturns = struct {
		result1 voldriver.Driver
		result2 error
	}{result1, result2}
}

func (fake *FakeDriverFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	fake.driverMutex.RLock()
	defer fake.driverMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDriverFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vollocal.DriverFactory = new(FakeDriverFactory)
