// This file was generated by counterfeiter
package volmanfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/volman"
)

type FakeClient struct {
	ListDriversStub        func() (volman.Drivers, error)
	listDriversMutex       sync.RWMutex
	listDriversArgsForCall []struct{}
	listDriversReturns     struct {
		result1 volman.Drivers
		result2 error
	}
}

func (fake *FakeClient) ListDrivers() (volman.Drivers, error) {
	fake.listDriversMutex.Lock()
	fake.listDriversArgsForCall = append(fake.listDriversArgsForCall, struct{}{})
	fake.listDriversMutex.Unlock()
	if fake.ListDriversStub != nil {
		return fake.ListDriversStub()
	} else {
		return fake.listDriversReturns.result1, fake.listDriversReturns.result2
	}
}

func (fake *FakeClient) ListDriversCallCount() int {
	fake.listDriversMutex.RLock()
	defer fake.listDriversMutex.RUnlock()
	return len(fake.listDriversArgsForCall)
}

func (fake *FakeClient) ListDriversReturns(result1 volman.Drivers, result2 error) {
	fake.ListDriversStub = nil
	fake.listDriversReturns = struct {
		result1 volman.Drivers
		result2 error
	}{result1, result2}
}

var _ volman.Client = new(FakeClient)
