// This file was generated by counterfeiter
package volmanfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/volman/voldriver"
	"github.com/pivotal-golang/lager"
)

type FakeDriver struct {
	InfoStub        func(logger lager.Logger) (voldriver.InfoResponse, error)
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
		logger lager.Logger
	}
	infoReturns struct {
		result1 voldriver.InfoResponse
		result2 error
	}
	MountStub        func(logger lager.Logger, mountRequest voldriver.MountRequest) (voldriver.MountResponse, error)
	mountMutex       sync.RWMutex
	mountArgsForCall []struct {
		logger       lager.Logger
		mountRequest voldriver.MountRequest
	}
	mountReturns struct {
		result1 voldriver.MountResponse
		result2 error
	}
	UnmountStub        func(logger lager.Logger, unmountRequest voldriver.UnmountRequest) error
	unmountMutex       sync.RWMutex
	unmountArgsForCall []struct {
		logger         lager.Logger
		unmountRequest voldriver.UnmountRequest
	}
	unmountReturns struct {
		result1 error
	}
}

func (fake *FakeDriver) Info(logger lager.Logger) (voldriver.InfoResponse, error) {
	fake.infoMutex.Lock()
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
		logger lager.Logger
	}{logger})
	fake.infoMutex.Unlock()
	if fake.InfoStub != nil {
		return fake.InfoStub(logger)
	} else {
		return fake.infoReturns.result1, fake.infoReturns.result2
	}
}

func (fake *FakeDriver) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *FakeDriver) InfoArgsForCall(i int) lager.Logger {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return fake.infoArgsForCall[i].logger
}

func (fake *FakeDriver) InfoReturns(result1 voldriver.InfoResponse, result2 error) {
	fake.InfoStub = nil
	fake.infoReturns = struct {
		result1 voldriver.InfoResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDriver) Mount(logger lager.Logger, mountRequest voldriver.MountRequest) (voldriver.MountResponse, error) {
	fake.mountMutex.Lock()
	fake.mountArgsForCall = append(fake.mountArgsForCall, struct {
		logger       lager.Logger
		mountRequest voldriver.MountRequest
	}{logger, mountRequest})
	fake.mountMutex.Unlock()
	if fake.MountStub != nil {
		return fake.MountStub(logger, mountRequest)
	} else {
		return fake.mountReturns.result1, fake.mountReturns.result2
	}
}

func (fake *FakeDriver) MountCallCount() int {
	fake.mountMutex.RLock()
	defer fake.mountMutex.RUnlock()
	return len(fake.mountArgsForCall)
}

func (fake *FakeDriver) MountArgsForCall(i int) (lager.Logger, voldriver.MountRequest) {
	fake.mountMutex.RLock()
	defer fake.mountMutex.RUnlock()
	return fake.mountArgsForCall[i].logger, fake.mountArgsForCall[i].mountRequest
}

func (fake *FakeDriver) MountReturns(result1 voldriver.MountResponse, result2 error) {
	fake.MountStub = nil
	fake.mountReturns = struct {
		result1 voldriver.MountResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDriver) Unmount(logger lager.Logger, unmountRequest voldriver.UnmountRequest) error {
	fake.unmountMutex.Lock()
	fake.unmountArgsForCall = append(fake.unmountArgsForCall, struct {
		logger         lager.Logger
		unmountRequest voldriver.UnmountRequest
	}{logger, unmountRequest})
	fake.unmountMutex.Unlock()
	if fake.UnmountStub != nil {
		return fake.UnmountStub(logger, unmountRequest)
	} else {
		return fake.unmountReturns.result1
	}
}

func (fake *FakeDriver) UnmountCallCount() int {
	fake.unmountMutex.RLock()
	defer fake.unmountMutex.RUnlock()
	return len(fake.unmountArgsForCall)
}

func (fake *FakeDriver) UnmountArgsForCall(i int) (lager.Logger, voldriver.UnmountRequest) {
	fake.unmountMutex.RLock()
	defer fake.unmountMutex.RUnlock()
	return fake.unmountArgsForCall[i].logger, fake.unmountArgsForCall[i].unmountRequest
}

func (fake *FakeDriver) UnmountReturns(result1 error) {
	fake.UnmountStub = nil
	fake.unmountReturns = struct {
		result1 error
	}{result1}
}

var _ voldriver.Driver = new(FakeDriver)
