// This file was generated by counterfeiter
package volmanfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/volman/remote"
)

type FakeRequestReturnInterface struct {
	AndReturnJsonInStub        func(jsonResponse interface{}) error
	andReturnJsonInMutex       sync.RWMutex
	andReturnJsonInArgsForCall []struct {
		jsonResponse interface{}
	}
	andReturnJsonInReturns struct {
		result1 error
	}
}

func (fake *FakeRequestReturnInterface) AndReturnJsonIn(jsonResponse interface{}) error {
	fake.andReturnJsonInMutex.Lock()
	fake.andReturnJsonInArgsForCall = append(fake.andReturnJsonInArgsForCall, struct {
		jsonResponse interface{}
	}{jsonResponse})
	fake.andReturnJsonInMutex.Unlock()
	if fake.AndReturnJsonInStub != nil {
		return fake.AndReturnJsonInStub(jsonResponse)
	} else {
		return fake.andReturnJsonInReturns.result1
	}
}

func (fake *FakeRequestReturnInterface) AndReturnJsonInCallCount() int {
	fake.andReturnJsonInMutex.RLock()
	defer fake.andReturnJsonInMutex.RUnlock()
	return len(fake.andReturnJsonInArgsForCall)
}

func (fake *FakeRequestReturnInterface) AndReturnJsonInArgsForCall(i int) interface{} {
	fake.andReturnJsonInMutex.RLock()
	defer fake.andReturnJsonInMutex.RUnlock()
	return fake.andReturnJsonInArgsForCall[i].jsonResponse
}

func (fake *FakeRequestReturnInterface) AndReturnJsonInReturns(result1 error) {
	fake.AndReturnJsonInStub = nil
	fake.andReturnJsonInReturns = struct {
		result1 error
	}{result1}
}

var _ remote.RequestReturnInterface = new(FakeRequestReturnInterface)
