// Code generated by counterfeiter. DO NOT EDIT.
package volmanfakes

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"code.cloudfoundry.org/volman"
)

type FakeDiscoverer struct {
	DiscoverStub        func(logger lager.Logger) (map[string]volman.Plugin, error)
	discoverMutex       sync.RWMutex
	discoverArgsForCall []struct {
		logger lager.Logger
	}
	discoverReturns struct {
		result1 map[string]volman.Plugin
		result2 error
	}
	discoverReturnsOnCall map[int]struct {
		result1 map[string]volman.Plugin
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDiscoverer) Discover(logger lager.Logger) (map[string]volman.Plugin, error) {
	fake.discoverMutex.Lock()
	ret, specificReturn := fake.discoverReturnsOnCall[len(fake.discoverArgsForCall)]
	fake.discoverArgsForCall = append(fake.discoverArgsForCall, struct {
		logger lager.Logger
	}{logger})
	fake.recordInvocation("Discover", []interface{}{logger})
	fake.discoverMutex.Unlock()
	if fake.DiscoverStub != nil {
		return fake.DiscoverStub(logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.discoverReturns.result1, fake.discoverReturns.result2
}

func (fake *FakeDiscoverer) DiscoverCallCount() int {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	return len(fake.discoverArgsForCall)
}

func (fake *FakeDiscoverer) DiscoverArgsForCall(i int) lager.Logger {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	return fake.discoverArgsForCall[i].logger
}

func (fake *FakeDiscoverer) DiscoverReturns(result1 map[string]volman.Plugin, result2 error) {
	fake.DiscoverStub = nil
	fake.discoverReturns = struct {
		result1 map[string]volman.Plugin
		result2 error
	}{result1, result2}
}

func (fake *FakeDiscoverer) DiscoverReturnsOnCall(i int, result1 map[string]volman.Plugin, result2 error) {
	fake.DiscoverStub = nil
	if fake.discoverReturnsOnCall == nil {
		fake.discoverReturnsOnCall = make(map[int]struct {
			result1 map[string]volman.Plugin
			result2 error
		})
	}
	fake.discoverReturnsOnCall[i] = struct {
		result1 map[string]volman.Plugin
		result2 error
	}{result1, result2}
}

func (fake *FakeDiscoverer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDiscoverer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ volman.Discoverer = new(FakeDiscoverer)
