#!/bin/bash
# vim: set ft=sh

set -e

cd volman/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

go get github.com/fzipp/gocyclo
go install github.com/fzipp/gocyclo

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

gocyclo -top 10 .
