#!/bin/bash
# vim: set ft=sh

set -e

cd diego-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

go install github.com/apcera/gnatsd
go install github.com/coreos/etcd
go get golang.org/x/tools/cmd/cover
go install golang.org/x/tools/cmd/cover
go install github.com/onsi/ginkgo/ginkgo

cd src/github.com/cloudfoundry-incubator/volman

ginkgo -cover -r

profiles=$(find . -name '*.coverprofile' | grep -v fake)

echo mode: set > all.coverprofile
cat $profiles | grep -v mode: >> all.coverprofile

cat all.coverprofile
