#!/bin/bash
# vim: set ft=sh

set -e

#chown -R diego diego-release/
#chown -R diego volman/

#rm -rf diego-release/src/github.com/cloudfoundry-incubator/volman/
#mkdir diego-release/src/github.com/cloudfoundry-incubator/volman/
#cp -R volman/* diego-release/src/github.com/cloudfoundry-incubator/volman/

export GIT_SSL_NO_VERIFY=true
git config --global user.name "Paul Warren"
git config --global user.email paul.warren@emc.com

echo "diego-release (branch: cf_persistence): rebasing onto develop"
pushd diego-release
git remote add local ../diego-release-mergeback
git fetch local develop
git rebase local/develop
popd

echo "diego-release (branch: cf_persistence): submodule update volman"
pushd diego-release/src/github.com/cloudfoundry-incubator
git submodule update --remote --merge volman
popd
#git submodule sync volman
#cd diego-release
#git add src/github.com/cloudfoundry-incubator/volman
#git commit -m "Concourse automatic bump to latest volman"

#su diego -c diego-release/src/github.com/cloudfoundry-incubator/volman/scripts/ci/run_cover
echo "volman (branch: master): run unit tests and gather coverage stats"
diego-release/src/github.com/cloudfoundry-incubator/volman/scripts/ci/run_cover

echo "diego-release (branch: cf_persistence): add changes and commit"
cd diego-release
git add src/github.com/cloudfoundry-incubator/volman
git commit -m "Concourse automatic bump to latest volman"
#git push origin cf_persistence