#!/bin/bash
# vim: set ft=sh

set -e

#chown -R diego diego-release/
#chown -R diego volman/

#rm -rf diego-release/src/github.com/cloudfoundry-incubator/volman/
#mkdir diego-release/src/github.com/cloudfoundry-incubator/volman/
#cp -R volman/* diego-release/src/github.com/cloudfoundry-incubator/volman/
pushd diego-release
git rebase origin/master
popd

pushd diego-release/src/github.com/cloudfoundry-incubator
git submodule update --remote --merge volman
popd
#git submodule sync volman
#cd diego-release
#git add src/github.com/cloudfoundry-incubator/volman
#git commit -m "Concourse automatic bump to latest volman"

#su diego -c diego-release/src/github.com/cloudfoundry-incubator/volman/scripts/ci/run_cover
diego-release/src/github.com/cloudfoundry-incubator/volman/scripts/ci/run_cover

cd diego-release
git config --global user.name "Paul Warren"
git config --global user.email paul.warren@emc.com
export GIT_SSL_NO_VERIFY=true
git add src/github.com/cloudfoundry-incubator/volman
git commit -m "Concourse automatic bump to latest volman"
#git push origin cf_persistence